name: "upload-release-action"
description: "Upload files to an existing GitHub release"
author: "Blaine Bublitz"
branding:
  icon: archive
  color: orange
inputs:
  token:
    description: "GitHub token for uploading assets to releases, defaults to using secrets.GITHUB_TOKEN"
    required: false
    default: ${{ github.token }}
  file:
    description: "Local file to upload"
    required: true
  tag:
    description: "Tag to find for the release"
    required: true
  asset_name:
    description: "Name of the asset attached to the release"
    required: true
  overwrite:
    description: "Overwrite the asset if it already exists"
    required: false
  repo_name:
    description: "Specify the name of the GitHub repository in which the GitHub release will modified. If the repository is other than the current, it is required to create a personal access token with `repo`, `user`, `admin:repo_hook` scopes to the foreign repository and add it as a secret. Defaults to the current repository"
    required: false
outputs:
  browser_download_url:
    description: "The publicly available URL of the asset"
  notes:
    description: "The body of the release"
runs:
  using: "node16"
  main: "dist/index.js"
